### ISSUE TITLE
[tracking] Alt e2eshark TODO's

### ISSUE THREAD

**Issue by zjgarvey** [nod-ai/SHARK-TestSuite#300]
Please feel free to contribute to this project by picking up one of the TODO items for alt_e2eshark

- [ ] look into using pytest or another testing framework.
- [ ] generate command-line reproducers for ease of debugging individual stages
- [ ] come up with a better name for the directory than "alt_e2eshark".
- [ ] identify functionality present in e2eshark that is currently lacking and should be migrated over. E.g. Chi's comment about the --report flag.
- [ ] add more type hints to make it easier to track down definitions.
- [ ] add (much) more to the README about adding tests and running them with various command line options.
- [ ] look into removing torch-mlir as a python dependency entirely (perhaps optionally, so torch-mlir developers can still use the test suite for debugging op conversions).
- [ ] Consider alternative options for storing cache directory paths, log directory paths, onnx model paths, etc. OnnxModelInfo is currently a bit clunky in needing to sometimes infer the log directory from the model path, etc.

**Comment by zjgarvey** [comment]
Ci Setup:
- [ ] flesh out report feature (maybe ignore time report)
- [ ] add a report merge feature
- [ ] testfile intake / registry
- [ ] register all of the tests we want to run
- [ ] maybe setup json configurable tests (and also automate the registry of such tests)
- [ ] have a option to report with smaller stages (5 from e2eshark)
