### ISSUE TITLE
[tracking] iree_tests onnx node test failures

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-TestSuite#324]
Genrated from: https://gist.github.com/renxida/2706b7522b38d8c6271bfff95fb62609

1. [ ] 181 test cases: `failed to legalize operation 'torch.operator' that was explicitly marked illegal`
2. [x] 59 test cases: `failed to legalize operation 'torch.aten.sum.dim_IntList' that was explicitly marked illegal` (being fixed at: https://github.com/llvm/torch-mlir/pull/3600)
3. [ ] 51 test cases: `failed to legalize operation 'torch.aten.nll_loss_forward' that was explicitly marked illegal`
4. [ ] 39 test cases: `found an op that was marked as backend illegal`
5. [ ] 12 test cases: `function is missing onnx opset version attribute (torch.onnx_meta.opset_version)`
6. [ ] 8 test cases: `failed to legalize operation 'torch.constant.int'`
7. [ ] 7 test cases: `failed to legalize operation 'torch.aten.cumsum' that was explicitly marked illegal`
8. [ ] 7 test cases: `unimplemented: dim is not constant`
9. [ ] 6 test cases: `failed to legalize operation 'torch.constant.bool'`
10. [ ] 6 test cases: `'tensor.cast' op operand type 'tensor<1x1x1xf32>' and result type 'tensor<f32>' are cast incompatible`
11. [ ] 6 test cases: `failed to legalize unresolved materialization from 'tensor<i64>' to 'tensor<1xi64>' that remained live after conversion`
12. [ ] 5 test cases: `failed to legalize operation 'torch.aten.nonzero'`
13. [ ] 5 test cases: `failed to legalize operation 'torch.aten.prod.dim_int' that was explicitly marked illegal`
14. [ ] 4 test cases: `unimplemented: non-floating point dtype`
15. [ ] 3 test cases: `'tensor.cast' op operand type 'tensor<1x1x1xf64>' and result type 'tensor<f64>' are cast incompatible`
16. [ ] 3 test cases: `'torch.aten.pad' op operand #3 must be Optional torch float type, but got '!torch.int'`
17. [ ] 2 test cases: `'tensor.expand_shape' op expected collapsed type to be 'tensor<2x2xi64>', but got 'tensor<2x2xf32>'`
18. [ ] 2 test cases: `failed to legalize operation 'torch.aten.fft_fft'`
19. [ ] 2 test cases: `'linalg.yield' op type of yield operand 1 ('i1') doesn't match the element type of the enclosing linalg.generic op ('f32')`
20. [ ] 1 test case: `failed to legalize operation 'torch.aten.fft_ifft'`
21. [ ] 1 test case: `'tensor.cast' op operand type 'tensor<1x1x2x2xf32>' and result type 'tensor<1x1x1x1xf32>' are cast incompatible`
22. [ ] 1 test case: `'torch.aten.permute' op expected input and output tensors to have same rank, but 3 != 2.`
23. [ ] 1 test case: `'tensor.cast' op operand type 'tensor<1x3x2xf32>' and result type 'tensor<3x1x2xf32>' are cast incompatible`
24. [ ] 1 test case: `'tensor.cast' op operand type 'tensor<f32>' and result type 'tensor<3xf32>' are cast incompatible`
25. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[?],f32>') doesn't match function result type ('!torch.vtensor<[2],f32>') in function @test_split_variable_parts_default_axis_opset13`
26. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[?],f32>') doesn't match function result type ('!torch.vtensor<[2],f32>') in function @test_split_variable_parts_default_axis_opset18`
27. [ ] 1 test case: `'arith.extsi' op operand #0 must be signless-fixed-width-integer-like, but got 'f8E4M3FN'`
28. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[3,4,5],si64>') doesn't match function result type ('!torch.vtensor<[3,4,5],f32>') in function @test_hardmax_axis_1`
29. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[2,?],f32>') doesn't match function result type ('!torch.vtensor<[2,2],f32>') in function @test_split_variable_parts_2d_opset18`
30. [ ] 1 test case: `'arith.fptosi' op result #0 must be signless-fixed-width-integer-like, but got 'f8E4M3FN'`
31. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[?],f32>') doesn't match function result type ('!torch.vtensor<[2],f32>') in function @test_split_variable_parts_1d_opset18`
32. [ ] 1 test case: `'tensor.cast' op operand type 'tensor<f32>' and result type 'tensor<5xf32>' are cast incompatible`
33. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[?],f32>') doesn't match function result type ('!torch.vtensor<[2],f32>') in function @test_split_variable_parts_1d_opset13`
34. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[2,?],f32>') doesn't match function result type ('!torch.vtensor<[2,2],f32>') in function @test_split_variable_parts_2d_opset13`
35. [ ] 1 test case: `'arith.fptosi' op result #0 must be signless-fixed-width-integer-like, but got 'f8E5M2'`
36. [ ] 1 test case: `type of return operand 0 ('!torch.vtensor<[3,4,5],si64>') doesn't match function result type ('!torch.vtensor<[3,4,5],f32>') in function @test_hardmax_axis_2`
37. [ ] 1 test case: `failed to materialize conversion for result #1 of operation 'torch.operator' that remained live after conversion`

**Comment by ScottTodd** [comment]
iree_tests onnx node tests moved to https://github.com/iree-org/iree-test-suites. Let's track there as needed.
